# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call('eeSNP_mvrnormArma', PACKAGE = 'eeSNP', n, mu, sigma)
}

eeSNP_regress <- function(x, y, feature, alpHa, beTa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn) {
    .Call('eeSNP_eeSNP_regress', PACKAGE = 'eeSNP', x, y, feature, alpHa, beTa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn)
}

find_correlation <- function(mask, x, y) {
    .Call('eeSNP_find_correlation', PACKAGE = 'eeSNP', mask, x, y)
}

filterSNP <- function(obj, parseFeature, threshold, threads) {
    .Call('eeSNP_filterSNP', PACKAGE = 'eeSNP', obj, parseFeature, threshold, threads)
}

filter_inconsequential <- function(mask, x, y, threshold) {
    .Call('eeSNP_filter_inconsequential', PACKAGE = 'eeSNP', mask, x, y, threshold)
}

cholGivensRotateLeft <- function(TT) {
    .Call('eeSNP_cholGivensRotateLeft', PACKAGE = 'eeSNP', TT)
}

cholAddCol <- function(TT, xx) {
    .Call('eeSNP_cholAddCol', PACKAGE = 'eeSNP', TT, xx)
}

pinvgammaC <- function(q, shape, scale, lower_tail = 1L, log_p = 0L) {
    .Call('eeSNP_pinvgammaC', PACKAGE = 'eeSNP', q, shape, scale, lower_tail, log_p)
}

rinvgammaC <- function(shape, scale) {
    .Call('eeSNP_rinvgammaC', PACKAGE = 'eeSNP', shape, scale)
}

epi_eQTL <- function(x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads) {
    .Call('eeSNP_epi_eQTL', PACKAGE = 'eeSNP', x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads)
}

filter_in <- function(obj, parseFeature, threshold) {
    .Call('eeSNP_filter_in', PACKAGE = 'eeSNP', obj, parseFeature, threshold)
}

ficorr <- function() {
    .Call('eeSNP_ficorr', PACKAGE = 'eeSNP')
}

