# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call('GOAL_mvrnormArma', PACKAGE = 'GOAL', n, mu, sigma)
}

eeSNP_regress <- function(x, y, feature, alpHa, beTa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn) {
    .Call('GOAL_eeSNP_regress', PACKAGE = 'GOAL', x, y, feature, alpHa, beTa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn)
}

find_correlation <- function(mask, x, y) {
    .Call('GOAL_find_correlation', PACKAGE = 'GOAL', mask, x, y)
}

filterSNP <- function(obj, parseFeature, threshold) {
    .Call('GOAL_filterSNP', PACKAGE = 'GOAL', obj, parseFeature, threshold)
}

filter_inconsequential <- function(mask, x, y, threshold) {
    .Call('GOAL_filter_inconsequential', PACKAGE = 'GOAL', mask, x, y, threshold)
}

univariate_eQTL <- function(mask2, x, y, numRegulators, threads = 1L) {
    .Call('GOAL_univariate_eQTL', PACKAGE = 'GOAL', mask2, x, y, numRegulators, threads)
}

multivariate_eQTL <- function(mask2, x, y, numRegulators, threads = 1L) {
    .Call('GOAL_multivariate_eQTL', PACKAGE = 'GOAL', mask2, x, y, numRegulators, threads)
}

cholGivensRotateLeft <- function(TT, inp) {
    .Call('GOAL_cholGivensRotateLeft', PACKAGE = 'GOAL', TT, inp)
}

cholAddCol <- function(TT, xx, inp) {
    .Call('GOAL_cholAddCol', PACKAGE = 'GOAL', TT, xx, inp)
}

pinvgammaC <- function(q, shape, scale, lower_tail = 1L, log_p = 0L) {
    .Call('GOAL_pinvgammaC', PACKAGE = 'GOAL', q, shape, scale, lower_tail, log_p)
}

rinvgammaC <- function(shape, scale) {
    .Call('GOAL_rinvgammaC', PACKAGE = 'GOAL', shape, scale)
}

epi_eQTL <- function(x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads, verbose = TRUE, balance = TRUE, logistic_variable_selection = TRUE, oversample = FALSE, sample_logit = FALSE, use_raoblackwell = TRUE, num_logit_train = 1000L, negtrain_num = 1000L, ratio = 1, gamMa_thres = .9, beTa_thres = .1, regulator_prior = 1.0/300.0, accIter = 1L, rho = 100.0, prior = .1) {
    .Call('GOAL_epi_eQTL', PACKAGE = 'GOAL', x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads, verbose, balance, logistic_variable_selection, oversample, sample_logit, use_raoblackwell, num_logit_train, negtrain_num, ratio, gamMa_thres, beTa_thres, regulator_prior, accIter, rho, prior)
}

epi_eQTL_dissecting <- function(x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads, verbose = TRUE, balance = TRUE, logistic_variable_selection = TRUE, oversample = FALSE, sample_logit = FALSE, use_raoblackwell = TRUE, num_logit_train = 1000L, ratio = .5, gamMa_thres = .9, beTa_thres = .1, regulator_prior = 1.0/300.0, accIter = 1L, rho = 1, prior = .1) {
    .Call('GOAL_epi_eQTL_dissecting', PACKAGE = 'GOAL', x, y, feature, pairFeature, mask2, alpHa, gamMa, estimate_alpha, estimate_beta, B_inv_alpHa, itermax, thin, burnIn, threads, verbose, balance, logistic_variable_selection, oversample, sample_logit, use_raoblackwell, num_logit_train, ratio, gamMa_thres, beTa_thres, regulator_prior, accIter, rho, prior)
}

